# Generated by Django 4.1.7 on 2023-02-21 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_flight_landing_time_alter_flight_takeoff_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='fname',
            new_name='f_name',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='lname',
            new_name='l_name',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='mname',
            new_name='m_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='fname',
            new_name='f_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lname',
            new_name='l_name',
        ),
    ]
