# Generated by Django 4.1.7 on 2023-02-27 14:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_rename_fname_reservation_f_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='SessionData',
            fields=[
                ('id', models.CharField(default='773058f23872146f159bc25a73c55a2a64e14804', max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flights.user')),
            ],
        ),
    ]
